spring.application.name=ADHD Resources
server.servlet.context-path=/api

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
logging.level.root=${LOGGING_LEVEL_ROOT}
